[package]
name = "burn_app"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.16.0", features = ["wgpu", "train", "vision"] }
bincode = { version = "2.0.0-rc.3", features = [
    "alloc",
    "serde",
], default-features = false }
